apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-pzcr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tenant/appstudio/dc-metro-map-pzcr@sha256:2283c8590534880cc1349224b7e50530d30cee7c47e2988dad29de2c2822bae3
        name: my-nodejs
        resources: {}
status: {}
